# Generated by Django 5.0.1 on 2024-01-24 15:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyitems', '0002_delete_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitems',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyitems',
            name='last_edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyitems',
            name='max_amount',
            field=models.IntegerField(default=8, help_text="At this amount, stock is at 'max recommended', above it is 'above max recommended'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyitems',
            name='med_amount',
            field=models.IntegerField(default=6, help_text="Below this amount, stock is at 'medium' amount"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyitems',
            name='min_amount',
            field=models.IntegerField(default=3, help_text="Below this amount, stock is 'low'"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyitems',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
