# Generated by Django 5.0.1 on 2024-01-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyitems', '0003_supplyitems_created_supplyitems_last_edited_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyitems',
            name='last_edited_by',
        ),
    ]
