# Generated by Django 5.0.1 on 2024-01-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyitems', '0004_remove_supplyitems_last_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyitems',
            name='created',
        ),
        migrations.RemoveField(
            model_name='supplyitems',
            name='updated',
        ),
    ]
