# Generated by Django 5.0.1 on 2024-01-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyitems', '0008_supplyitem_image_supplyitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about product stock management of this item.', null=True),
        ),
    ]
