# Generated by Django 5.0.1 on 2024-01-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyitems', '0010_alter_supplyitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
