# Generated by Django 5.0.1 on 2024-01-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyitems', '0011_alter_supplyitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
